version: "3"
services:
  receipt-processor:
    container_name: receipt-processor-compose
    build:
      context: .
      dockerfile: Dockerfile
    image: receipt-processor-compose:latest
    ports:
      - 8080:8080
